# Generated by Django 2.2.6 on 2019-11-11 00:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_polls_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='users',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, default=list, null=True, size=300),
        ),
    ]
