# Generated by Django 2.2.6 on 2019-11-13 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_userresponses'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponses',
            name='poll',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='polls.Polls'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userresponses',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='account'),
        ),
    ]
